### ISSUE TITLE
@swc/jest creates an incorrect coverage report

### ISSUE THREAD

**Issue by hheimerd** [swc-project/pkgs#32] opened 2024-03-26 13:42 UTC
I set up the project as described in the instructions, but the jest coverage is generated incorrectly:
1. Arrow functions that return jsx with specified pops without curly brackets are not included in the coverage. 
2. imports are included in the coverage
3. exports are included in the coverage

I made a minimal case and included coverage files in the repository
https://github.com/hheimerd/swc-jest-report

<img width="600" alt="Screenshot 2024-03-26 at 14 25 53" src="https://github.com/swc-project/pkgs/assets/38163258/1e527b7f-36d4-40be-b39f-ff13cf479aa5">

P.S. if you set sourceMaps to true, the internal functions will be included in the report, which is also strange

**Comment by mateus4k** [comment] 2024-06-06 15:02
Hey, did you find any solution for this?

**Comment by kdy1** [comment] 2024-06-11 07:50
Duplicate of https://github.com/swc-project/swc/issues/3854

**Closed by kdy1** 2024-06-11 07:50 UTC
